<script>
  aurl = 'mailing';
</script>

<div class="content-wrapper">

  <section class="content">

    <div class="row">

      <div class="col-xs-12">

        <div class="box">

          <div class="box-header">

            <h3 class="box-title">Mailing panel
            </h3>

          </div>
          <!-- /.box-header -->

          <div class="col-xs-12">

            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Utwórz nową wiadomość</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Zobacz wysłane wiadomości</a>


          </div>

          <form class="cd-form floating-labels">
            <fieldset>

              <div class="error-message">
                <p>office@buziak.pl</p>
              </div>

              <div class="icon">

                <div class="icon">
                  <label class="cd-label" for="cd-company">Send message to</label>
                  <input class="company" type="text" name="cd-company" id="cd-company" value="All users" disabled>
                </div>

                <div class="icon">
                  <label class="cd-label" for="cd-email">Subject</label>
                  <input class="company" type="text" name="cd-company" id="cd-company">
                </div>

                <div>
                  <h4>Attach a file</h4>

                  <p class="cd-select icon">
                    <select class="budget">
                      <option value="0">Select Budget</option>
                      <option value="1">&lt; $5000</option>
                      <option value="2">$5000 - $10000</option>
                      <option value="3">&gt; $10000</option>
                    </select>
                  </p>
                </div>

                <div>
                  <h4>Message type</h4>

                  <ul class="cd-form-list">
                    <li>
                      <input type="radio" name="radio-button" id="cd-radio-1" checked>
                      <label for="cd-radio-1">html</label>
                    </li>

                    <li>
                      <input type="radio" name="radio-button" id="cd-radio-2">
                      <label for="cd-radio-2">txt</label>
                    </li>
                  </ul>
                </div>

                <div class="icon">
                  <label class="cd-label" for="cd-textarea">message</label>
                  <textarea class="message" name="cd-textarea" id="cd-textarea" required></textarea>
                </div>

                <div>
                  <input type="submit" value="Send Message">
                </div>
            </fieldset>
          </form>

          </div>
          <!-- /.box -->

        </div>

      </div>

  </section>

  </div>