<!-- Content Wrapper. Contains page content -->

<div class="content-wrapper">


  <!-- Content Header (Page header) -->

  <section class="content-header">

    <h1>

      Payment settings

    </h1>

  </section>

  <script>
    aurl = 'payment';
  </script>

  <!-- Main content -->

  <section class="content">

  <div class="row">

        <div class="col-xs-12">

          <div class="box">

            <div class="box-header">

            <a href="index.php?page=admin&p=payment" class="box-title" style="padding: 0px 10px 0px 10px;">Wszystkie</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Opłacone</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Nieopłacone</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">SMS</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">PayPal</a>
            <a href="index.php?page=admin&p=reports" class="box-title" style="padding: 0px 10px 0px 10px;">Skrill</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Staty</a>
            <a href="index.php?page=admin&p=paymentc" class="box-title" style="padding: 0px 10px 0px 10px;">Konfiguracja</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Skrill - transakcje</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Skrill - trans. problemowe</a>
            <a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Za dużo dni</a>

            </div>
            <!-- /.box-header -->

          </div>
          <!-- /.box -->

        </div>

      </div>


 

</div>

</section>

</div>