<?php

	$photos_rev = getTotalPhotosReview();

	$f = secureEncode($_GET['f']);

	?>

	<div class="content-wrapper">

		<section class="content-header">

			<?php if($f == 1){ 

          echo '<h1>Total photos</h1>';

		 }  if($f == 2){ 

          echo '<h1>Photos for review</h1>';

		 }  if($f == 3){ 

          echo '<h1>Private photos</h1>';

		 } 

		?>

		</section>

		<script>
			aurl = 'photos';
		</script>

		<section class="content">


			<div class="row">

				<div class="col-xs-12">

					<div class="box">

						<div class="box-header">
							<a href="index.php?page=admin&p=photos&f=1" class="box-title" style="padding: 0px 10px 0px 10px;">Wszystkie (
									<?= getTotalPhotos(1); ?>)</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Aktywni</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Duże (+free Premium)</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Duże HOT</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Wersja mobilna</a>
							<a href="index.php?page=admin&p=photos&f=2" class="box-title" style="padding: 0px 10px 0px 10px;">Do zatwierdzenia (
									<span data-review-photos="<?= $photos_rev; ?>">
										<?= $photos_rev; ?>
									</span>)</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Nie przycięte?</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Do spraw. główne</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Do spraw. dodatkowe</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Do zatw. opisy</a>
							<a href="index.php?page=admin&p=photos&f=3" class="box-title" style="padding: 0px 10px 0px 10px;">Wszystkie prywatne (
									<span data-private-photos="<?= getTotalPhotosPrivate(); ?>">
										<?= getTotalPhotosPrivate(); ?>
									</span>)</a>
							<a href="index.php?page=admin&p=photos&f=" class="box-title" style="padding: 0px 10px 0px 10px;">Do zatw. prywatne</a>

						</div>
						<!-- /.box-header -->

					</div>
					<!-- /.box -->

				</div>

			</div>


			<div class="row">

				<div class='col-md-12'>

					<div class="box box">

						<div class="box-header with-border">

							<h3 class="box-title">Manage photos click and press "1" for approve, "2" for discard , "3" for private and "W" for view</h3>

						</div>
						<!-- /.box-header -->

						<div class="box-body no-padding">

							<ul class="users-list clearfix">

								<?php  $d = 0;

							if($_GET['x'] != ''){

								$x = secureEncode($_GET['x']);

								$d = $x * 50; 

							}

							echo getAdminPhotos($f,$d);

						?>

							</ul>
							<!-- /.users-list -->

						</div>
						<!-- /.box-body -->

						<div class="box-footer clearfix">

							<ul class="pagination pagination-sm no-margin pull-right">

								<?php if($d > 0){ ?>

								<li>
									<a href="index.php?page=admin&p=photos&f=<?= $f;?>&x=<?= $x-1;?>">Previous page (
										<?= $x-1;?>)</a>
								</li>

								<li>
									<a href="index.php?page=admin&p=photos&f=<?= $f;?>&x=<?= $x+1;?>">Next page (
										<?= $x+1;?>)</a>
								</li>

								<?php } else { ?>

								<li>
									<a href="index.php?page=admin&p=photos&f=<?= $f;?>&x=1">Next page</a>
								</li>

								<?php } ?>



							</ul>

						</div>

					</div>
					<!--/.box -->

				</div>
				<!-- /.col -->

			</div>
			<!-- /.box -->

	</div>

	</div>

	</section>

	</div>