      <!-- Content Wrapper. Contains page content -->

      <div class="content-wrapper">

        <!-- Content Header (Page header) -->

        <section class="content-header">

          <h1>

            Script Installed themes

          </h1>

        </section>

		<script>aurl = 'themes';</script>

        <!-- Main content -->

        <section class="content">

          <div class="row">

            <div class="col-md-3">

				<?= getAdminThemesLanding(); ?>

			</div>

            <div class="col-md-3">

				<?= getAdminThemesFrontEnd(); ?>

			</div>

            <div class="col-md-3">

				<?= getAdminThemesMobile(); ?>

			</div>

            <div class="col-md-3">

				<?= getAdminThemesEmail(); ?>

			</div>		

		</div>		
		

		

		

	</section>

</div>	