<script>
	url = "visits";
</script>
<?php $fans = totalVisitsTwoo($sm['user']['id']); ?>
<?php if($sm['user']['premium'] == 0 && $sm['basic']['visits'] == 0){ ?>
<?php if($fans == 0){ ?>
<div class="visits">
	<div class="container relative">
		<?php if($sm['user']['premium'] == 0 && siteConfig('ads') != ''){				echo '<div data-ad="1" style="position:relative;width:100%;height:90px;top:10px;">'.siteConfig('ads').'</div>';				}			?>
		<div class="visits-container">
			<h1>
				<?= $sm['twoo_lang'][144]['text']; ?> :(</h1>
			<h4>
				<?= $sm['twoo_lang'][145]['text']; ?>
			</h4>
			
			<center>
				<a href="#" data-open-premium-modal="1">
					<span class="activate-premium">
						<?= $sm['twoo_lang'][44]['text']; ?>
					</span>
				</a>
			</center>
		</div>
	</div>
</div>
<?php } else { ?>
<div class="visits">
	<div class="container relative">
		<div class="visits-container">
			<h1>
				<span data-main-color="1">
					<?= $fans?>
						<?= $sm['twoo_lang'][146]['text']; ?>
				</span>
				<?= $sm['twoo_lang'][147]['text']; ?>
			</h1>
			<h4>
				<?= $sm['twoo_lang'][148]['text']; ?>
			</h4>
			<div class="peek">
				<center>
					<?= getUserVisitorsPeekTwoo($sm['user']['id']); ?>
				</center>
			</div>
			<h4>
				<?= $sm['twoo_lang'][149]['text']; ?>
			</h4>
			<center>
				<a href="#" data-open-premium-modal="1">
					<span class="activate-premium">
						<?= $sm['twoo_lang'][44]['text']; ?>
					</span>
				</a>
			</center>
		</div>
	</div>
</div>
<?php } ?>
<?php } else { ?>
<?php $visitors = getUserVisitorsTwoo($sm['user']['id']); 			if($visitors == ''){ ?>
<div class="discover">
	<div class="container relative">
		<?php if($sm['user']['premium'] == 0 && siteConfig('ads') != ''){
				echo '<div data-ad="1" style="position:relative;width:100%;height:90px;top:10px;">'.siteConfig('ads').'</div>';
				}
 ?>
		<div class="left-content">
			<h3>
				<?= $sm['twoo_lang'][150]['text']; ?>:(</h3>
		</div>
		<div class="right-adsection">
			<?= siteConfig('ads2'); ?>
		</div>
	</div>
</div>
<?php } else { ?>
<div class="discover">
	<div class="container relative">
		<div class="left-content">
			<h3>
				<?= $sm['twoo_lang'][151]['text']; ?>
			</h3>
			<ul>
				<?= $visitors;?>
			</ul>
		</div>
		<div class="right-adsection">
			<?= siteConfig('ads2'); ?>
		</div>
	</div>
</div>
<?php } ?>
<?php } ?>