
						<div class="card-panel photo" data-src="<?=$sm['photo']['src']; ?>" id="pid<?=$sm['photo']['id']; ?>" data-blocked="<?=$sm['photo']['blocked']; ?>">
                            <div class="data" src="<?=$sm['photo']['src']; ?>" 
							data-id='<?=$sm['photo']['id']; ?>'
							data-user='<?=$sm['photo']['user']; ?>'
							data-photo='<?=$sm['photo']['photo']; ?>'
							data-like='<?=$sm['photo']['like']; ?>' 
							data-likes='<?=$sm['photo']['likes']; ?>' 
							data-desc='<?=$sm['photo']['desc']; ?>' 
							data-comments='<?=$sm['photo']['comments']; ?>'
							>
								<a href="javasacript:;" data-delete-photo="true" data-pid="<?=$sm['photo']['id']; ?>" data-tooltip="Delete"><i class="mdi-action-delete"></i></a> 							
								<? if($sm['photo']['blocked'] == 1){ ?>
									<a href="javasacript:;" data-unblock-photo="true" data-pid="<?=$sm['photo']['id']; ?>"   data-tooltip="Public photo" ><i class="mdi-action-lock-open"></i></a> 
								<? } else { ?>
									<a href="javasacript:;" data-block-photo="true" data-pid="<?=$sm['photo']['id']; ?>" data-tooltip="Prviate photo" ><i class="mdi-action-lock-outline"></i></a>									
								<? } ?>								
								<a href="javasacript:;" data-set-profile="true" data-pid="<?=$sm['photo']['id']; ?>"  data-tooltip="Set as profile" ><i class="mdi-image-portrait"></i></a>
                            </div>
                        </div>