	<script>
	url = "settings";
	</script> 

	<div class="discover">
        <div class="container relative">    
            <div class="left-content-settings">
            	<div class="settings-section">
                    <h1><?= $sm['twoo_lang'][122]['text']; ?></h1>
                    <h4><?= $sm['twoo_lang'][123]['text']; ?></h4>
                    <div class="hr"></div>
					<form class="form-horizontal"  method="post" id="update-profile">
					  <div class="form-group">
						<label class="col-sm-2 control-label"><?= $sm['twoo_lang'][124]['text']; ?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="name" value="<?= $sm['user']['name']; ?>">
						</div>
					  </div>
					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][28]['text']; ?>:</label>
						<div class="col-sm-10">
							<input type="text" class="form-control" name="email" value="<?= $sm['user']['email']; ?>">
						</div>
					  </div>
					  <?php  $timestamp = strtotime($sm['user']['birthday']); ?>
					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['twoo_lang'][125]['text']; ?></label>
						<div class="col-sm-3">
							<input type="text" class="form-control" name="day" value="<?= date("d", $timestamp); ?>">
						</div>
						<div class="col-sm-3">
							<input type="text" class="form-control" name="month" value="<?= date("m", $timestamp); ?>">
						</div>
						<div class="col-sm-4">
							<input type="text" class="form-control" name="year" value="<?= date("Y", $timestamp); ?>">
						</div>						
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['twoo_lang'][126]['text']; ?></label>
						<div class="col-sm-10">
							<input type="text" class="form-control"  id="loc" value="<?= $sm['user']['city']; ?>">
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['twoo_lang'][127]['text']; ?></label>
						<div class="col-sm-10">
							<textarea type="text" class="form-control"  id="bio" name="bio" rows="3"><?= $sm['user']['bio']; ?> </textarea>
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['twoo_lang'][128]['text']; ?></label>
						<div class="col-sm-10">
							<select class="form-control" name="lang">
								<option value="<?= $sm['user']['lang']; ?>"> <?= getCurrentLang($sm['user']['lang']); ?> </option>
								<?= getSiteLangs($sm['user']['lang']); ?>
							</select>
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][34]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="gender">
							<?php  if($sm['user']['gender'] == 1){ ?>
								<option value="1"> <?= $sm['lang'][35]['text']; ?> </option>
								<option value="2"> <?= $sm['lang'][36]['text']; ?> </option>
							<?php  } else { ?>
								<option value="2"> <?= $sm['lang'][36]['text']; ?> </option>							
								<option value="1"> <?= $sm['lang'][35]['text']; ?> </option>								
							<?php  } ?>
							</select>						
						</div>
					  </div>					  
					<input type="hidden" value="update" name="action" />
					<input type="hidden" name="city" id="locality" value="<?= $sm['user']['city']; ?>" />
					<input type="hidden" name="country" id="country" value="<?= $sm['user']['country']; ?>"  />
					<input type="hidden" name="lat" id="lat" value="<?= $sm['user']['lat']; ?>"  />					
					<input type="hidden" name="lng" id="lng" value="<?= $sm['user']['lng']; ?>"  />
					
					<div class="hr"></div>
					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][223]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended1">
								<option value="<?= $sm['user']['extended']['field1']; ?>"><?= $sm['user']['extended']['field1']; ?></option>
								<option value="<?= $sm['lang'][224]['text']; ?>"><?= $sm['lang'][224]['text']; ?></option>
								<option value="<?= $sm['lang'][225]['text']; ?>"><?= $sm['lang'][225]['text']; ?></option>
								<option value="<?= $sm['lang'][226]['text']; ?>"><?= $sm['lang'][226]['text']; ?></option>
							</select>						
						</div>
					  </div>
					  
					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][227]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended2">
									<option value="<?= $sm['user']['extended']['field2']; ?>"><?= $sm['user']['extended']['field2']; ?></option>
									<option value="<?= $sm['lang'][228]['text']; ?>"><?= $sm['lang'][228]['text']; ?></option>
									<option value="<?= $sm['lang'][229]['text']; ?>"><?= $sm['lang'][229]['text']; ?></option>
									<option value="<?= $sm['lang'][230]['text']; ?>"><?= $sm['lang'][230]['text']; ?></option>
									<option value="<?= $sm['lang'][231]['text']; ?>"><?= $sm['lang'][231]['text']; ?></option>	
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][232]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended3">
									<option value="<?= $sm['user']['extended']['field3']; ?>"><?= $sm['user']['extended']['field3']; ?></option>
									<option value="<?= $sm['lang'][233]['text']; ?> 4' 7' (140cm)"><?= $sm['lang'][233]['text']; ?> 4' 7' (140cm)</option>
									<option value="4' 8' (142cm)">4' 8' (142cm)</option>	
									<option value="4' 9' (145cm)">4' 9' (145cm)</option>	
									<option value="4' 10' (147cm)">4' 10' (147cm)</option>	
									<option value="4' 11' (150cm)">4' 11' (150cm)</option>	
									<option value="5' 0' (152cm)">5' 0' (152cm)</option>	
									<option value="5' 1' (155cm)">5' 1' (155cm)</option>	
									<option value="5' 2' (157cm)">5' 2' (157cm)</option>	
									<option value="5' 3' (160cm)">5' 3' (160cm)</option>	
									<option value="5' 4' (163cm)">5' 4' (163cm)</option>	
									<option value="5' 5' (162cm)">5' 5' (165cm)</option>	
									<option value="5' 6' (168cm)">5' 6' (168cm)</option>	
									<option value="5' 7' (170cm)">5' 7' (170cm)</option>	
									<option value="5' 8' (173cm)">5' 8' (173cm)</option>	
									<option value="5' 9' (175cm)">5' 9' (175cm)</option>	
									<option value="5' 10' (178cm)">5' 10' (178cm)</option>	
									<option value="5' 11' (180cm)">5' 11' (180cm)</option>	
									<option value="6' 0' (183cm)">6' 0' (183cm)</option>	
									<option value="6' 1' (185cm)">6' 1' (185cm)</option>	
									<option value="6' 2' (188cm)">6' 2' (188cm)</option>	
									<option value="6' 3' (191cm)">6' 3' (191cm)</option>
									<option value="6' 4' (193cm)">6' 4' (193cm)</option>
									<option value="6' 5' (196cm)">6' 5' (196cm)</option>
									<option value="6' 6' (198cm)">6' 6' (198cm)</option>
									<option value="6' 7' (201cm)">6' 7' (201cm)</option>
									<option value="6' 8' (203cm)">6' 8' (203cm)</option>
									<option value="6' 9' (206cm)">6' 9'(206cm)</option>
									<option value="6' 10' (208cm)">6' 10' (208cm)</option>
									<option value="6' 11' (211cm)">6' 11' (211cm)</option>
									<option value="7' 0' (213cm)">7' 0' (213cm)</option>
									<option value="7' 1' (216cm)">7' 1' (216cm)</option>
									<option value="7' 2' (218cm)">7' 2' (218cm)</option>
									<option value="<?= $sm['lang'][234]['text']; ?> 7' 3' (220cm)"><?= $sm['lang'][234]['text']; ?> 7' 3' (220cm)</option>									
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][235]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended4">
									<option value="<?= $sm['user']['extended']['field4']; ?>"><?= $sm['user']['extended']['field4']; ?></option>
									<option value="<?= $sm['lang'][233]['text']; ?> 86lbs (39kg)"><?= $sm['lang'][233]['text']; ?> 86lbs (39kg)</option>
									<option value="88 lbs (40kg)">88 lbs (40kg)</option>	
									<option value="90 lbs (41kg)">90 lbs (41kg)</option>	
									<option value="93 lbs (42kg)">93 lbs (42kg)</option>	
									<option value="95 lbs (43kg)">95 lbs (43kg)</option>	
									<option value="97 lbs (44kg)">97 lbs (44kg)</option>	
									<option value="99 lbs (45kg)">99 lbs (45kg)</option>	
									<option value="101 lbs (46kg)">101 lbs (46kg)</option>	
									<option value="104 lbs (47kg)">104 lbs (47kg)</option>	
									<option value="106 lbs (48kg)">106 lbs (48kg)</option>	
									<option value="108 lbs (49kg)">108 lbs (49kg)</option>	
									<option value="110 lbs (50kg)">110 lbs (50kg)</option>	
									<option value="112 lbs (51kg)">112 lbs (51kg)</option>	
									<option value="115 lbs (52kg)">115 lbs (52kg)</option>	
									<option value="117 lbs (53kg)">117 lbs (53kg)</option>	
									<option value="119 lbs (54kg)">119 lbs (54kg)</option>	
									<option value="121 lbs (55kg)">121 lbs (55kg)</option>	
									<option value="123 lbs (56kg)">123 lbs (56kg)</option>	
									<option value="126 lbs (57kg)">126 lbs (57kg)</option>	
									<option value="128 lbs (58kg)">128 lbs (58kg)</option>	
									<option value="130 lbs (59kg)">130 lbs (59kg)</option>	
									<option value="132 lbs (60kg)">132 lbs (60kg)</option>	
									<option value="134 lbs (61kg)">134 lbs (61kg)</option>	
									<option value="137 lbs (62kg)">137 lbs (62kg)</option>	
									<option value="139 lbs (63kg)">139 lbs (63kg)</option>	
									<option value="141 lbs (64kg)">141 lbs (64kg)</option>	
									<option value="143 lbs (65kg)">143 lbs (65kg)</option>	
									<option value="145 lbs (66kg)">145 lbs (66kg)</option>	
									<option value="148 lbs (67kg)">148 lbs (67kg)</option>	
									<option value="150 lbs (68kg)">150 lbs (68kg)</option>	
									<option value="152 lbs (69kg)">152 lbs (69kg)</option>	
									<option value="154 lbs (70kg)">154 lbs (70kg)</option>	
									<option value="156 lbs (71kg)">156 lbs (71kg)</option>	
									<option value="159 lbs (72kg)">159 lbs (72kg)</option>	
									<option value="161 lbs (73kg)">161 lbs (73kg)</option>	
									<option value="163 lbs (74kg)">163 lbs (74kg)</option>	
									<option value="165 lbs (75kg)">165 lbs (75kg)</option>	
									<option value="167 lbs (76kg)">167 lbs (76kg)</option>	
									<option value="170 lbs (77kg)">170 lbs (77kg)</option>	
									<option value="172 lbs (78kg)">172 lbs (78kg)</option>	
									<option value="174 lbs (79kg)">174 lbs (79kg)</option>	
									<option value="176 lbs (80kg)">176 lbs (80kg)</option>	
									<option value="178 lbs (81kg)">178 lbs (81kg)</option>	
									<option value="181 lbs (82kg)">181 lbs (82kg)</option>	
									<option value="183 lbs (83kg)">183 lbs (83kg)</option>	
									<option value="185 lbs (84kg)">185 lbs (84kg)</option>	
									<option value="187 lbs (85kg)">187 lbs (85kg)</option>	
									<option value="189 lbs (86kg)">189 lbs (86kg)</option>	
									<option value="192 lbs (87kg)">192 lbs (87kg)</option>	
									<option value="194 lbs (88kg)">194 lbs (88kg)</option>	
									<option value="196 lbs (89kg)">196 lbs (89kg)</option>	
									<option value="198 lbs (90kg)">198 lbs (90kg)</option>	
									<option value="200 lbs (91kg)">200 lbs (91kg)</option>	
									<option value="203 lbs (92kg)">203 lbs (92kg)</option>	
									<option value="205 lbs (93kg)">205 lbs (93kg)</option>	
									<option value="207 lbs (94kg)">207 lbs (94kg)</option>	
									<option value="209 lbs (95kg)">209 lbs (95kg)</option>	
									<option value="211 lbs (96kg)">211 lbs (96kg)</option>	
									<option value="214 lbs (97kg)">214 lbs (97kg)</option>
									<option value="216 lbs (98kg)">216 lbs (98kg)</option>
									<option value="218 lbs (99kg)">218 lbs (99kg)</option>
									<option value="220 lbs (100kg)">220 lbs (100kg)</option>
									<option value="222 lbs (101kg)">222 lbs (101kg)</option>
									<option value="225 lbs (102kg)">225 lbs (102kg)</option>
									<option value="227 lbs (103kg)">227 lbs (103kg)</option>
									<option value="229 lbs (104kg)">229 lbs (104kg)</option>
									<option value="231 lbs (105kg)">231 lbs (105kg)</option>
									<option value="233 lbs (106g)">233 lbs (106kg)</option>
									<option value="236 lbs (107kg)">236 lbs (107kg)</option>
									<option value="238 lbs (108kg)">238 lbs (108kg)</option>
									<option value="240 lbs (109kg)">240 lbs (109kg)</option>
									<option value="242 lbs (110kg)">242 lbs (110kg)</option>
									<option value="244 lbs (111kg)">244 lbs (111kg)</option>
									<option value="247 lbs (112kg)">247 lbs (112kg)</option>
									<option value="249 lbs (113kg)">249 lbs (113kg)</option>
									<option value="251 lbs (114kg)">251 lbs (114kg)</option>
									<option value="253 lbs (115kg)">253 lbs (115kg)</option>
									<option value="255 lbs (116kg)">255 lbs (116kg)</option>
									<option value="258 lbs (117kg)">258 lbs (117kg)</option>
									<option value="260 lbs (118kg)">260 lbs (118kg)</option>
									<option value="262 lbs (119kg)">262 lbs (119kg)</option>
									<option value="<?= $sm['lang'][234]['text']; ?> 264 lbs (120kg)"><?= $sm['lang'][234]['text']; ?> 264 lbs (120kg)</option>
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][236]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended5">
								<option value="<?= $sm['user']['extended']['field5']; ?>"><?= $sm['user']['extended']['field5']; ?></option>
								<option value="<?= $sm['lang'][237]['text']; ?>"><?= $sm['lang'][237]['text']; ?></option>
								<option value="<?= $sm['lang'][238]['text']; ?>"><?= $sm['lang'][238]['text']; ?></option>
								<option value="<?= $sm['lang'][239]['text']; ?>"><?= $sm['lang'][239]['text']; ?></option>
								<option value="<?= $sm['lang'][240]['text']; ?>"><?= $sm['lang'][240]['text']; ?></option>
								<option value="<?= $sm['lang'][241]['text']; ?>"><?= $sm['lang'][241]['text']; ?></option>
								<option value="<?= $sm['lang'][242]['text']; ?>"><?= $sm['lang'][242]['text']; ?></option>
								<option value="<?= $sm['lang'][243]['text']; ?>"><?= $sm['lang'][243]['text']; ?></option>
								<option value="<?= $sm['lang'][244]['text']; ?>"><?= $sm['lang'][244]['text']; ?></option>
								<option value="<?= $sm['lang'][245]['text']; ?>"><?= $sm['lang'][245]['text']; ?></option>	
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][246]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended6">
									<option value="<?= $sm['user']['extended']['field6']; ?>"><?= $sm['user']['extended']['field6']; ?></option>
									<option value="<?= $sm['lang'][247]['text']; ?>"><?= $sm['lang'][247]['text']; ?></option>
									<option value="<?= $sm['lang'][248]['text']; ?>"><?= $sm['lang'][248]['text']; ?></option>
									<option value="<?= $sm['lang'][249]['text']; ?>"><?= $sm['lang'][249]['text']; ?></option>
									<option value="<?= $sm['lang'][250]['text']; ?>"><?= $sm['lang'][250]['text']; ?></option>
									<option value="<?= $sm['lang'][251]['text']; ?>"><?= $sm['lang'][251]['text']; ?></option>	
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][252]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended7">
									<option value="<?= $sm['user']['extended']['field7']; ?>"><?= $sm['user']['extended']['field7']; ?></option>
									<option value="<?= $sm['lang'][253]['text']; ?>"><?= $sm['lang'][253]['text']; ?></option>
									<option value="<?= $sm['lang'][254]['text']; ?>"><?= $sm['lang'][254]['text']; ?></option>
									<option value="<?= $sm['lang'][255]['text']; ?>"><?= $sm['lang'][255]['text']; ?></option>
									<option value="<?= $sm['lang'][256]['text']; ?>"><?= $sm['lang'][256]['text']; ?></option>
									<option value="<?= $sm['lang'][257]['text']; ?>"><?= $sm['lang'][257]['text']; ?></option>
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][258]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended8">
									<option value="<?= $sm['user']['extended']['field8']; ?>"><?= $sm['user']['extended']['field8']; ?></option>
									<option value="<?= $sm['lang'][259]['text']; ?>"><?= $sm['lang'][259]['text']; ?></option>
									<option value="<?= $sm['lang'][260]['text']; ?>"><?= $sm['lang'][260]['text']; ?></option>
									<option value="<?= $sm['lang'][261]['text']; ?>"><?= $sm['lang'][261]['text']; ?></option>
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][262]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended9">
									<option value="<?= $sm['user']['extended']['field9']; ?>"><?= $sm['user']['extended']['field9']; ?></option>
									<option value="<?= $sm['lang'][259]['text']; ?>"><?= $sm['lang'][259]['text']; ?></option>
									<option value="<?= $sm['lang'][260]['text']; ?>"><?= $sm['lang'][260]['text']; ?></option>
									<option value="<?= $sm['lang'][261]['text']; ?>"><?= $sm['lang'][261]['text']; ?></option>
							</select>						
						</div>
					  </div>

					  <div class="form-group">
						<label  class="col-sm-2 control-label"><?= $sm['lang'][263]['text']; ?>:</label>
						<div class="col-sm-10">
							<select class="form-control" name="extended10">
									<option value="<?= $sm['user']['extended']['field10']; ?>"><?= $sm['user']['extended']['field10']; ?></option>
									<option value="<?= $sm['lang'][264]['text']; ?>"><?= $sm['lang'][264]['text']; ?></option>
									<option value="<?= $sm['lang'][265]['text']; ?>"><?= $sm['lang'][265]['text']; ?></option>
									<option value="<?= $sm['lang'][266]['text']; ?>"><?= $sm['lang'][266]['text']; ?></option>
									<option value="<?= $sm['lang'][267]['text']; ?>"><?= $sm['lang'][267]['text']; ?></option>
							</select>						
						</div>
					  </div>					  
					  
					<div class="col-sm-12">
						<p id="update-error" class="bg-danger" style="padding:15px;border-radius:5px;display:none"></p>
						<p id="update-success" class="bg-success" style="padding:15px;border-radius:5px;display:none"></p>
					</div>	
				
					  <div class="form-group">
						<div class="col-sm-offset-2 col-sm-10">
						  <button type="submit" class="btn btn-default btn-right"><?= $sm['twoo_lang'][129]['text']; ?></button>
						</div>
					  </div>	
					</form>
                </div>
            	<div class="settings-section">
                    <h1><?= $sm['twoo_lang'][130]['text']; ?></h1>
                    <div class="hr"></div>
					<form class="form-horizontal"  method="post">
					  <div class="form-group">
						<label class="col-sm-8 control-label" style="text-align:left;float:left"><?= $sm['twoo_lang'][131]['text']; ?></label>
						<div class="col-sm-4">
							<label class="radio-inline">
							  <input name="fans" type="radio" value="1"  <?php  if($sm['user_notifications']['fan'] == 1){echo 'checked';} ?> id="yes1" /> <?= $sm['twoo_lang'][132]['text']; ?>
							</label>
							<label class="radio-inline">
							  <input name="fans" type="radio" value="0"  <?php  if($sm['user_notifications']['fan'] == 0){echo 'checked';} ?> id="no1" /> <?= $sm['twoo_lang'][133]['text']; ?>
							</label>
						</div>
					  </div>
					  <div class="form-group">
						<label class="col-sm-8 control-label" style="text-align:left;float:left;"><?= $sm['twoo_lang'][134]['text']; ?> <3</label>
						<div class="col-sm-4">
							<label class="radio-inline">
							  <input name="match_m" type="radio" value="1"  <?php  if($sm['user_notifications']['match_m'] == 1){echo 'checked';} ?> id="yes4" /> <?= $sm['twoo_lang'][132]['text']; ?>
							</label>
							<label class="radio-inline">
							  <input name="match_m" type="radio" value="0"  <?php  if($sm['user_notifications']['match_m'] == 0){echo 'checked';} ?> id="no4" /> <?= $sm['twoo_lang'][133]['text']; ?>
							</label>
						</div>
					  </div>
					  <div class="form-group">
						<label class="col-sm-8 control-label" style="text-align:left;float:left;"><?= $sm['twoo_lang'][135]['text']; ?></label>
						<div class="col-sm-4">
							<label class="radio-inline">
							  <input name="near" type="radio" value="1"  <?php  if($sm['user_notifications']['near_me'] == 1){echo 'checked';} ?> id="yes2" /> <?= $sm['twoo_lang'][132]['text']; ?>
							</label>
							<label class="radio-inline">
							  <input name="near" type="radio" value="0"  <?php  if($sm['user_notifications']['near_me'] == 0){echo 'checked';} ?> id="no2" /> <?= $sm['twoo_lang'][133]['text']; ?>
							</label>
						</div>
					  </div>
					  <div class="form-group">
						<label class="col-sm-8 control-label" style="text-align:left;float:left;"><?= $sm['twoo_lang'][136]['text']; ?></label>
						<div class="col-sm-4">
							<label class="radio-inline">
							  <input name="message" type="radio" value="1"  <?php  if($sm['user_notifications']['message'] == 1){echo 'checked';} ?> id="yes3" /> <?= $sm['twoo_lang'][132]['text']; ?>
							</label>
							<label class="radio-inline">
							  <input name="message" type="radio" value="0"  <?php  if($sm['user_notifications']['message'] == 0){echo 'checked';} ?> id="no3" /> <?= $sm['twoo_lang'][133]['text']; ?>
							</label>
						</div>
					  </div>					  
					</form>					  
                </div>

            	<div class="settings-section">
                    <h1><?= $sm['twoo_lang'][137]['text']; ?></h1>
                    <h4><?= $sm['twoo_lang'][138]['text']; ?></h4>
                    <div class="hr"></div>
					<form class="form-horizontal"  method="post" id="change-password">
					  <div class="form-group">
						<label class="col-sm-3 control-label" style="text-align:left;float:left;"><?= $sm['twoo_lang'][139]['text']; ?></label>
						<div class="col-sm-9">
							<input type="password" class="form-control"  name="new_password" value="">
							<input type="hidden" name="action" value="changep"   >
						</div>
					  </div>				
					  <div class="form-group">
						<div class="col-sm-12">
						  <button type="submit" id="change-pwd-btn" class="btn btn-default btn-right"><?= $sm['twoo_lang'][137]['text']; ?></button>
						</div>
					  </div>	
					</form>
                </div>
				
            	<div class="settings-section">
                    <h1><?= $sm['twoo_lang'][140]['text']; ?></h1>
                    <h4><?= $sm['twoo_lang'][141]['text']; ?>	</h4>
					<a class="btn btn-danger" id="delete-acc"  href="#" ><?= $sm['twoo_lang'][142]['text']; ?></a>
					<br><br>			
                </div>				

				
            </div>
            
            <div class="right-credits-section">
            	<div class="header">
                	<h2><?= $sm['config']['name']; ?> <?= $sm['twoo_lang'][17]['text']; ?></h2>
                    <center><div class="total-credits"><?= $sm['user']['credits']; ?> <?= $sm['twoo_lang'][17]['text']; ?></div>
           			<a href="#" data-open-credits-modal="1"><span class="buy-credits">+ <?= $sm['twoo_lang'][17]['text']; ?></span></a></center>
                </div>
            </div>
            
        </div>
    </div>
				
					
