	  <? $lang = secureEncode($_GET['id']);?>
      <div class="content-wrapper">
		<script>aurl = 'lang';</script>	  
        <section class="content">
          <div class="row">
            <div class="col-md-12">
              <!-- general form elements -->
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Lindoo app lang - <?= getCurrentLang($lang); ?></h3>
                </div><!-- /.box-header -->
                  <div class="box-body">
					  <div class="row">
						<?= getAdminLangEditApp($lang); ?>							
						
					</div>
                  </div>
              </div><!-- /.box -->
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Tinder - <?= getCurrentLang($lang); ?></h3>
                </div><!-- /.box-header -->
                  <div class="box-body">
					  <div class="row">
						<?= getAdminLangEditTinder($lang); ?>							
						
					</div>
                  </div>
              </div><!-- /.box -->
			  
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Social Match - <?= getCurrentLang($lang); ?> - Tinder uses some info from bellow so please update it too</h3>
                </div><!-- /.box-header -->
                  <div class="box-body">
					  <div class="row">			  
						<?= getAdminLangEdit($lang); ?>
					</div>
                  </div>
              </div><!-- /.box -->				  
			  
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Email - <?= getCurrentLang($lang); ?></h3>
                </div><!-- /.box-header -->
                  <div class="box-body">
					  <div class="row">			  
						<?= getAdminLangEditEmail($lang); ?>
					</div>
                  </div>
              </div><!-- /.box -->			  
			</div>		
		</div>	
	</section>
</div>	
		</div>