    <?php require_once 'assets/sources/client.php'; ?>
	  <div class="content-wrapper">

        <section class="content">


        <div class="row">
        <div class="col-md-6">
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Fake user settings</h3>
                  <p style="color:#999"></p>
                </div><!-- /.box-header -->
                <!-- form start -->
               <form action="#" id="fakeu-settings">
                <input type="hidden" value="fakeu" name="action" />               
                  <div class="box-body">
                    <div class="form-group">
                      <label for="exampleInputEmail1">Chance to visit back</label>
                      <p style="color:#999">If the fake user is online chance to visit back after visit</p>
                      <input class="form-control" value="<?= siteConfig('visit_back'); ?>%" name="fakeu_visit" />
                    </div>
                    <div class="form-group">
                      <label for="exampleInputEmail1">Chance to like back</label>
                      <p style="color:#999">If the fake user is online chance to visit back after visit</p>
                      <input class="form-control" value="<?= siteConfig('like_back'); ?>%" name="fakeu_like" />
                    </div>                            
                  </div><!-- /.box-body -->
                  <div class="box-footer">
                    <button type="submit" class="btn btn-primary" >Update fake user settings</button>            
                  </div>
                </form>
              </div><!-- /.box -->
              </div>

          <div class="col-md-6">
              <div class="box box-primary">
                <div class="box-header">
                  <h3 class="box-title">Fake users statics</h3>
                  <p style="color:#999"></p>
                </div> 
                <div class="box-body">  
                  <div class="progress-group">
                    <span class="progress-text">Created Users / Max users</span>
                    <span class="progress-number"><b><?= getTotalUsers(4); ?></b>/<span><?= $sm['fakeUsers']; ?></span></span>

                    <div class="progress sm">
                      <div class="progress-bar progress-bar-aqua" id="fp"></div>
                    </div>
                  </div>
                  <!-- /.progress-group -->
                  <div class="progress-group">
                    <span class="progress-text">Artificial Intelligence replies</span>
                    <span class="progress-number"><b><?= $sm['fakeAIUsage']; ?></b>/<?= $sm['fakeAI']; ?></span>

                    <div class="progress sm">
                      <div class="progress-bar progress-bar-yellow" id="air"></div>
                    </div>
                  </div>
                  </div>
                  </div>
                </div>
        </div>        
	</section>

</div>		

 <script>aurl = 'sfake';
 var totalF = <?= getTotalUsers(4); ?>;
 totalF = parseInt(totalF);
 var totalFP = Math.floor((totalF / <?= $sm['fakeUsers']; ?>) * 100);
 document.getElementById('fp').style.width = totalFP+'%';

var totalAI = <?= $sm['fakeAIUsage']; ?>;
 totalAI = parseInt(totalAI);
 var totalAIR = Math.floor((totalAI / <?= $sm['fakeAI']; ?>) * 100);
 document.getElementById('air').style.width = totalAIR+'%';
 </script>  