<!doctype html>
	<head>
		<title><?php echo $sm['config']['title']; ?></title>

		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

		<?php
		 if($sm['config']['ios'] != ''){
			$id = end(explode('/id', parse_url($sm['config']['ios'], PHP_URL_PATH)));
			echo '<meta name="apple-itunes-app" content="app-id='.$id.'">';
		 }

		 if($sm['config']['android'] != ''){
		 	$id = end(explode('=', $sm['config']['android']));
		 	echo '<meta name="google-play-app" content="app-id='.$id.'">';
		 }
		 ?>		 

		<meta name="description" content="<?php echo $sm['config']['description']; ?>">

		<meta name="keywords" content="<?php echo $sm['config']['keywords']; ?>">

		<meta name="author" content="<?php echo $sm['config']['name']; ?>">		

		<noscript>		

		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/assets/css/skel.css" />

		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/assets/css/style.css" />

		</noscript>

		<link rel="stylesheet" href="<?php echo $sm['config']['theme_url_landing']; ?>/assets/css/jquery.smartbanner.css" type="text/css" media="screen">
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/jquery.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/jquery.dropotron.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/jquery.scrollgress.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/skel.min.js"></script>

		<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url']; ?>/assets/css/sweetalert.css">		

		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/skel-layers.min.js"></script>


		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=<?= siteConfig('google_maps'); ?>"></script>	
		
		<style>

		/* Preloader */

		#preloader {

			position: fixed;

			top:0;

			left:0;

			right:0;

			bottom:0;

			background:#fff;

		  height:100%;

		  width:100%;

			z-index:999999; /* makes sure it stays on top */

		}



		#status {

			width:200px;

			height:200px;

			position:absolute;

			left:50%; /* centers the loading animation horizontally one the screen */

			top:50%; /* centers the loading animation vertically one the screen */

			margin:-100px 0 0 -100px; /* is width and height divided by two */

		}

		</style>

		<?php

		$location = json_decode(file_get_contents('http://freegeoip.net/json/'.$_SERVER['REMOTE_ADDR']));

		$site_config = json_encode($sm['config']);

		$site_lang = json_encode($sm['lang']);

		$filter_age = 0;

		echo 

		'<script>

		var url;

		var mobile = false;		

		var site_config = '. $site_config  . ';

		var site_lang = '. $site_lang  . ';

		function request_source(){

			return \'' . $sm['config']['ajax_path'] . '\';

		}

		function site_title(){

			return \'' . $sm['config']['title'] . '\';

		}	

		function theme_source(){

			return \'' . $sm['config']['theme_url'] . '\';

		}

		function site_url(){

			return \'' . $sm['config']['site_url'] . '\';

		}	

		var current_user_id = 0;

		var user_name;	

		</script>';

		?>		

	</head>

	<body class="landing">

			<div id="preloader">

				<div id="status"><div class="profile-outer-ring"></div></div>

			</div>	

			<header id="header" class="alt">

				<nav id="nav">

				  <ul>

						<li>

							<a href="javascript:;" class="icon fa-angle-down"><span class="icon fa-globe"></span></a>

							<ul> 

                            <table>

                            <tr>

								<?= getSiteLangsIndex(0,6); ?>                          

                            </tr>

								<?= getSiteLangsIndex(6,6); ?>  

                            <tr>                        

                            </tr>

								<?= getSiteLangsIndex(12,6); ?>

                            <tr>                           

                            </tr>

								<?= getSiteLangsIndex(18,6); ?>

                            <tr>                          

                            </tr> 

								<?= getSiteLangsIndex(24,6); ?>

                            <tr>                          

                            </tr>

								<?= getSiteLangsIndex(30,6); ?>

                            <tr>                           

                            </tr>

								<?= getSiteLangsIndex(36,6); ?>

                            <tr>                           

                            </tr>

								<?= getSiteLangsIndex(42,6); ?>

                            <tr>                          

                            </tr>  

                            </table>                           

                       		</ul>

						</li>						

						<li><a href="javascript:;" data-login="true" class="button special"><?= $sm['lang'][1]['text']; ?></a></li>

					</ul>

				</nav>

			</header>

			<div class="main">

				<video  loop autoplay loop muted playsinline width="1280" height="720" style="display:none">
					<source type="video/mp4" src="<?= $sm['config']['theme_url_landing']; ?>/assets/images/bg.mp4">

				</video>		  

				<div class="left"  >

					<div class="top-logo">

						<center><img src="<?= $sm['config']['logo_landing']; ?>" /></center>

					</div>

					<div class="header-text">

						<h1><?= $sm['lang'][0]['text']; ?> <b id="cityName"><?= $location->city; ?></b></h1>

					</div>

					

					<div class="latest-users">

						<center><?= getLatestUsersProfilePhoto(); ?></center>

					</div>

					<div id="mobileOnly" style="display: none;position:absolute;top:400px;left:40px;">
						<? if($sm['config']['android'] != ''){ ?>

							<a href="<?= $sm['config']['android']; ?>" target="_blank" style="border:none"><img src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/images/playstore.png" style="display:inline;margin-right:10px;height:50px;"></a>

						<? } if($sm['config']['ios'] != ''){ ?>	

							<a href="<?= $sm['config']['ios']; ?>" target="_blank" style="border:none;"><img src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/images/appstore.png" style="display:inline;margin-right:10px;height:50px;"></a>

						<? } ?>
					</div>

					<div class="button" data-j>

						<a href="#" data-join> <?= $sm['lang'][24]['text']; ?> </a>

					</div>

				</div>

				<div class="right" id="forms" style="display:none;">

					<div class="box">

						<div class="header">

							<? if(siteConfig('fb_app_id') != '') { ?>

							<a href="index.php?social=fb">

								<div class="fb"> 

									<div class="logo">

										<i class="icon fa-facebook"></i>

									</div>

									<h3><? $sign = explode(' ',$sm['lang'][13]['text']); echo $sign[0]; ?></h3>								

								</div>

							</a>

							<? } if(siteConfig('twitter_key') != ''){ ?>

							<a href="index.php?social=twitter">

								<div class="twitter"> 

									<div class="logo">

										<i class="icon fa-twitter"></i>

									</div>

									<h3><? $sign = explode(' ',$sm['lang'][13]['text']); echo $sign[0]; ?></h3>								

								</div>

							</a>

							<? } if(siteConfig('google_key') != '' || siteConfig('instagram_key') != ''){  ?>							

							<div class="more"> 

								<div class="logo">

									<i id="more-icon" class="icon fa-ellipsis-h"></i>

								</div>								

							</div>

							<? } ?>

						</div>

						<div class="socials">

							<ul>

							  <? if(siteConfig('instagram_key') != ''){ ?>

							  <a href="index.php?social=instagram">

								<li><img src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/images/insta.jpg">Instagram</li>

							  </a>

							  <? } if(siteConfig('google_key') != ''){  ?>

							  <a href="index.php?social=google">

								<li><img src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/images/google.jpg">Google</li>

							  </a>

							  <? } ?>

							  

							</ul>								

						</div>

						<div id="login-form"  style="display:none;">

							<div class="title">

								<h1><?= $sm['lang'][380]['text']; ?> <?= $sm['config']['name']; ?></h1>

							</div>

							<div class="form">

								<form method="post" action="#" id="login" style="margin:0;padding:0;">

								<input type="hidden" value="login" name="action" />

								<input type="email" name="login_email" id="login_email" required placeholder="<?= $sm['lang'][10]['text']; ?>"  />

								<input type="password" name="login_pass" id="login_pass" required placeholder="<?= $sm['lang'][11]['text']; ?>"  />

								</form>

								<div class="12u 12u(mobilep)" style="text-align:right; font-size:14px; padding-right:40px; color:#888;" >

									<a href="javascript:;" id="recover-pwd"><?= $sm['lang'][12]['text']; ?></a>

								</div>

								<div class="error"  id="login-error"></div>

								<div class="signup" id="login-now"><?= $sm['lang'][13]['text']; ?></div>

								<div class="info">

									<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 

									<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>								

								</div>

							</div>							

						</div>

						<div id="recover-form"  style="display:none;">

							<div class="title">

								<h1><?= $sm['lang'][14]['text']; ?></h1>

							</div>

							<div class="form">

								<form method="post" action="#" id="recover" style="margin:0;padding:0;">

								<input type="hidden" value="recover" name="action" />

								<input type="email" name="recover_email" id="recover_email" required placeholder="<?= $sm['lang'][10]['text']; ?>"  />

								</form>

								<div class="error"  id="recover-error"></div>

								<div class="signup" id="recover-now"><?= $sm['lang'][15]['text']; ?></div>

								<div class="info">

									<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 

									<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>								

								</div>

							</div>							

						</div>						

						<div id="register-form" style="z-index: 99999">

							<div class="title">

								<h1><?= $sm['lang'][24]['text']; ?></h1>

							</div>

							<div class="form">

								<form method="post" action="#" id="register" style="margin:0;padding:0;">

								<input type="text"  name="name" maxlength="18" id="name" required placeholder="<?= $sm['lang'][27]['text']; ?>" />

								<input type="email" name="email" required id="email" placeholder="<?= $sm['lang'][10]['text']; ?>"  />

								<input type="password" name="pass" id="pass" required placeholder="<?= $sm['lang'][11]['text']; ?>" />

								<select name="day" id="day" style="width:22%;" required >

									<option value="1" disabled selected hidden ><?= $sm['lang'][272]['text']; ?></option>

									<?= date_dropdown(1); ?>

								</select>

								<select name="month"  id="month"  style="width:32%;margin-left:10px" required>						

									<option value="1" disabled selected hidden><?= $sm['lang'][273]['text']; ?></option>

									<?= date_dropdown(0,1); ?>

								</select>

								<select name="year" id="year" style="width:23%;margin-left:10px" required >

									<option value="1990" disabled selected hidden><?= $sm['lang'][274]['text']; ?></option>							

									<?= date_dropdown(0,0,1); ?>

								</select>

								
								<input type="text" name="loc" id="loc" required value='<?= $location->city; ?>' placeholder="<?= $sm['lang'][33]['text']; ?>" />
							
								<select name="gender" style="cursor:pointer;width:38%;margin-left:10px"  id="gender" placeholder="<?= $sm['lang'][31]['text']; ?>">

									<option value="1" style="color:#000;"><?= $sm['lang'][35]['text']; ?></option>

									<option value="2" style="color:#000;"><?= $sm['lang'][36]['text']; ?></option>

								</select>

								<select name="looking" style="cursor:pointer;width:45%;margin-left:10px" id="looking" placeholder="<?= $sm['lang'][31]['text']; ?>">

									<option value="2" style="color:#000;"><?= $sm['lang'][38]['text']; ?></option>

									<option value="1" style="color:#000;"><?= $sm['lang'][39]['text']; ?></option>

									<option value="3" style="color:#000;"><?= $sm['lang'][40]['text']; ?></option>                                

								</select>

								<input type="hidden" value="register" name="action" />

								<input type="hidden" name="city" id="locality" value="<?= $location->city; ?>"/>

								<input type="hidden" name="country" id="country" value="<?= $location->country_name; ?>"  />

								<input type="hidden" name="lat" id="lat" value="<?= $location->latitude; ?>" />

								<input type="hidden" name="lng" id="lng" value="<?= $location->longitude; ?>"  />

								</form>

								<div class="error"  id="error"></div>

								<div class="signup" id="create-acc"><?= $sm['lang'][41]['text']; ?></div>

								<div class="info">

									<?= $sm['lang'][42]['text']; ?> <a href="<?= $sm['config']['site_url']; ?>/index.php?page=tac" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=tac','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][43]['text']; ?> </a> <?= $sm['lang'][44]['text']; ?> 

									<a href="<?= $sm['config']['site_url']; ?>/index.php?page=pp" style="color:#aaa;" onclick="javascript:void window.open('<?= $sm['config']['site_url']; ?>/index.php?page=pp','1430115090715','width=700,height=500,toolbar=0,menubar=0,location=0,status=1,scrollbars=1,resizable=1,left=0,top=0');return false;"><?= $sm['lang'][45]['text']; ?></a>								

								</div>

							</div>

						</div>						

					</div>

				</div>

				<div class="fbottom" style="z-index: 9999">

					

					<div style="float:left;padding-left:5px;margin-bottom:20px;">

						<span style="float:left;margin-left:12px;font-weight:500;font-size:38px;color:#fff;padding-bottom:10px;">
						<?php $total = getTotalUsers(3);  ?><?= number_format($total); ?></span><br>

						<span style="float:left;margin-left:12px;font-size:20px;color:#fff;margin-bottom:5px;"><?= $sm['lang'][108]['text']; ?></span>

					</div>

					<div style="float:right;padding-right:10px;">

					<? if($sm['config']['android'] != ''){ ?>

						<a href="<?= $sm['config']['android']; ?>" target="_blank" style="border:none"><img src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/images/playstore.png" style="display:inline;margin-right:10px;height:50px;"></a>

					<? } if($sm['config']['ios'] != ''){ ?>	

						<a href="<?= $sm['config']['ios']; ?>" target="_blank" style="border:none;"><img src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/images/appstore.png" style="display:inline;margin-right:10px;height:50px;"></a>

					<? } ?>

					</div>					

					<div class="line"></div>

				</div>				

			</div>

 	

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/jquery.preload.js"></script>

		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/dynamics.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/sweetalert.min.js"></script> 

		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/init.js"></script>
		<script src="<?php echo $sm['config']['theme_url_landing']; ?>/assets/js/jquery.smartbanner.js"></script>
		<?= siteConfig('js'); ?>		
		<script type="text/javascript">
		var w = $(window).width();	

		$('video')[0].play();

		$('video')[0].pause();		

		$(window).load(function() {		

			var h = $(window).height();	

			$('.main').css('height',h+'px'); 

			$('#status').fadeOut(); // will first fade out the loading animation

			$('#preloader').delay(350).fadeOut('slow'); // will fade out the white DIV that covers the website.

			$('body').delay(350).css({'overflow':'visible'});

			var position = $('#cityName').offset();

			var maxW = $('#cityName').width();

			var left = position.left - 5;

			$('.latest-users').css('left',left+'px');		

			setTimeout(function(){

				$('video')[0].play();

				$('video').show(); 

			},1500);

			var xaxa = 0;

				setTimeout(function(){

				var show_search = setInterval(function(){	

					if(xaxa == 7){

						clearInterval(show_search);				

					}

					$('[data-search-show='+xaxa+']').fadeIn();

					xaxa++;					

				},300);

			},1500);			

			$('body').keyup(function(e) {

				switch (e.keyCode) {

					case 13: // Enter

						$('#login-now').click();

					break;

				}

			});

			

			$('[data-join]').click(function(e){

				e.preventDefault();

				$('[data-j]').hide();

				$('.header-text').hide();

				$('.latest-users').hide();

				$('.top-logo img').addClass('scale-logo');

				setTimeout(function(){

					$('#forms').fadeIn();

				},300);				

				$('.top-logo').animate({								 

					top: '-10px'

					}, 500, function() {

				});				

			});

			$('select').change(function(e){

				$(this).css('color','#333');

			});

			

			$('.more').click(function(e){

				e.preventDefault();

				if($('.socials').css('opacity') == 0){

					show();

					$('#more-icon').removeClass('fa-ellipsis-h');

					$('#more-icon').addClass('fa-close');

				} else {

					hide();

					$('#more-icon').removeClass('fa-close');							

					$('#more-icon').addClass('fa-ellipsis-h');							

				}

			});					

			var nav = document.querySelector('.socials')

			var items = document.querySelectorAll('.socials ul li')



			function show() {

			  // Animate the popover

			  dynamics.animate(nav, {

				opacity: 1,

				scale: 1

			  }, {

				type: dynamics.spring,

				frequency: 200,

				friction: 270,

				duration: 800

			  })


			  for(var i=0; i<items.length; i++) {

				var item = items[i]

				// Define initial properties

				dynamics.css(item, {

				  opacity: 0,

				  translateY: 20

				})
				dynamics.animate(item, {

				  opacity: 1,

				  translateY: 0

				}, {

				  type: dynamics.spring,

				  frequency: 300,

				  friction: 435,

				  duration: 1000,

				  delay: 100 + i * 40
				})
			  }
			}
			function hide() {
			  dynamics.animate(nav, {

				opacity: 0,

				scale: .1

			  }, {

				type: dynamics.easeInOut,

				duration: 300,

				friction: 100

			  })

			}
		})
		 $(function() {
	   		 $.smartbanner({ title:'<?= $sm['config']['name']; ?>' });	
	     });
		function detect_device(val) {

			var w = window,

				d = document,

				e = d.documentElement,

				g = d.getElementsByTagName('body')[0],

				x = w.innerWidth || e.clientWidth || g.clientWidth,

				y = w.innerHeight|| e.clientHeight|| g.clientHeight;

			var isiPhone = 		navigator.userAgent.toLowerCase().indexOf("iphone");

			var isiPad = 		navigator.userAgent.toLowerCase().indexOf("ipad");

			var isiPod = 		navigator.userAgent.toLowerCase().indexOf("ipod");

			var isiAndroid = 	navigator.userAgent.toLowerCase().indexOf("android");
			if(x <= 600){
				$('.header-text').css('width',x+'px');
				$('.top-logo').css('width',x+'px');
				$('.fbottom').css('width',x+'px');
				var g = x/1.1;
				$('.left .button').css('width',g+'px');
				$('.left .button').hide();
				$('#header').hide();
				$('#mobileOnly').show();
				$('.latest-users').hide();
			} else {
				if(val == 1){
					window.location.href = '<?= $sm['config']['site_url']; ?>';
				}
			}
		}
		detect_device(0);
		$( window ).resize(function() {
		  detect_device(1);
		});
		</script> 		

	</body>

</html>