<!doctype html>

<head>
	<title>
		<?php echo $sm['config']['title']; ?>
	</title>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

	<meta name="description" content="<?php echo $sm['config']['description']; ?>" />

	<meta name="keywords" content="<?php echo $sm['config']['keywords']; ?>" />

	<meta name="author" content="<?php echo $sm['config']['name']; ?>" />

	<link href="<?php echo $sm['config']['theme_url']; ?>/assets/css/bootstrap.css" type="text/css" rel="stylesheet" />

	<link href="<?php echo $sm['config']['theme_url']; ?>/assets/css/tinder-theme.css" type="text/css" rel="stylesheet" />

	<link href="<?php echo $sm['config']['theme_url']; ?>/assets/css/emoticons.css" rel="stylesheet" type="text/css" />

	<link rel="stylesheet" type="text/css" href="<?php echo $sm['config']['theme_url']; ?>/assets/css/sweetalert.css">

	<link rel="stylesheet" href="<?php echo $sm['config']['theme_url']; ?>/assets/css/hint.css" />

	<link rel="stylesheet" href="<?php echo $sm['config']['theme_url']; ?>/assets/css/scroller.css" />

	<link rel="stylesheet" href="<?php echo $sm['config']['theme_url']; ?>/assets/css/wdt-emoji-bundle.css" />

	<link href="<?php echo $sm['config']['theme_url']; ?>/assets/css/fbphotobox.css" rel="stylesheet" type="text/css" />
	<link href="<?php echo $sm['config']['theme_url']; ?>/assets/css/app_ad.css" rel="stylesheet" type="text/css" />

	<link href='https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900' rel='stylesheet' type='text/css'>

	<link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>

	<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<!--noew fonty -->
	<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css'>
	<link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i|Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i|Varela+Round" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">

<link rel="stylesheet" href="https://anandchowdhary.github.io/ionicons-3-cdn/icons.css" integrity="sha384-+iqgM+tGle5wS+uPwXzIjZS5v6VkqCUV7YQ/e/clzRHAxYbzpUJ+nldylmtBWCP0" crossorigin="anonymous">
<!--noew fonty -->

	<?php  $actual_link = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; ?>

	<?= getPlugins('css_file'); ?>
		<script>
		
			//psuje się ax52
			var mainColor = '<?= $sm['config']['main_color'];?>';
			//psuje się ax52

			function d_d() {

				var w = window,

					d = document,

					e = d.documentElement,

					g = d.getElementsByTagName('body')[0],

					x = w.innerWidth || e.clientWidth || g.clientWidth,

					y = w.innerHeight || e.clientHeight || g.clientHeight;

				var isiPhone = navigator.userAgent.toLowerCase().indexOf("iphone");

				var isiPad = navigator.userAgent.toLowerCase().indexOf("ipad");

				var isiPod = navigator.userAgent.toLowerCase().indexOf("ipod");

				var isiAndroid = navigator.userAgent.toLowerCase().indexOf("android");

				if (isiPhone > -1 || isiPad > -1 || isiPod > -1 || isiAndroid > -1) {

					//window.location = "<?=$sm['config']['site_url'];?>/mobile.php";
					window.location = "<?=$sm['config']['site_url'];?>/app";

				}

				if (x <= 600) {
					//window.location = "<?=$sm['config']['site_url'];?>/mobile.php";
					window.location = "<?=$sm['config']['site_url'];?>/app";
				}

			}

			d_d();

		</script>

		<?php

$site_config = json_encode($sm['config']);
$site_prices = json_encode($sm['price']);
$account_basic = json_encode($sm['basic']);
$account_premium = json_encode($sm['premium']);
$site_lang = json_encode($sm['lang']);
$twoo_lang = json_encode($sm['twoo_lang']);
$user_info = json_encode($sm['user']);
$filter_age = 0;
echo 

'<script>

var url;
var mobile = false;
var chatLimit = false;var userPo = '.$sm['user']['total_photos'].';
var site_config = '. $site_config  . ';
var site_prices = '. $site_prices  . ';
var account_basic = '. $account_basic  . ';
var account_premium = '. $account_premium  . ';
var site_lang = '. $site_lang  . ';
var twoo_lang = '. $twoo_lang  . ';
var user_info = '. $user_info  . ';

function request_source(){

	return \'' . $sm['config']['ajax_path'] . '\';

}

function site_title(){

	return \'' . $sm['config']['title'] . '\';

}	

function theme_source(){

	return \'' . $sm['config']['theme_url'] . '\';

}

function site_url(){

	return \'' . $sm['config']['site_url'] . '\';

}	

function user_id(){

	return \'' . $sm['user']['id'] . '\';

}

var current_user_id = 0;

var user_name;	

</script>';

?>

			<?= siteConfig('css');?>

</head>

<body>

	<?php include('modal.php'); ?>

	<!-- edit space -->

	<div class="page-content">

		<div class="page-left">

			<?php $nav = 2; ?>



			<?php if($nav == 1){ ?>

			<?php include('modules/nav1.php');?>

			<?}else if($nav == 2){?>

				<?php include('modules/nav2.php');?>

				<?php } ?>


		</div>

		<div class="page-right">

			<!-- START MAIN CONTENT -->

			<?php $top = 2; ?>



			<?php if($top == 1){ ?>

			<?php include('modules/top1.php');?>

			<?}else if($top == 2){?>

				<?php include('modules/top2.php');?>

				<?php } ?>


			<div id="data-content">

				<?php echo $sm['content']; ?>

			</div>

			<!-- END MAIN CONTENT -->

		</div>

	</div>

	<?php include('footer.php') ?>

	<!-- edit space -->

	<?php
	if(!isset($_COOKIE['appAd']) && $sm['user']['total_photos'] > 0) {
		setcookie('appAd', 1,time()+(3600*24*3));
	?>
		<div class="interstial-wrap">
			<center>
				<div class="interstial-main-box">
					<a class="interstial-close" onclick="document.querySelector('.interstial-wrap').style.display = 'none';"></a>
					<div class="interstial-app-screen" data-main-background="1">
						<div class="interstial-app-screen-img">
							<img src="<?php echo $sm['config']['theme_url']; ?>/images/appScreen.png" alt="apps">
						</div>
					</div>
					<div class="interstial-content">
						<div class="interstial-logo">
							<a href="">
								<img src="<?= $sm['config']['logo']; ?>" alt="image">
							</a>
						</div>
						<div class="interstial-intro-text">
							Download the
							<?= $sm['config']['name']; ?> app and take full advantage of social networking. Keep in touch, find out new "likes" and find interesting people
								easily! </div>
						<div class="interstial-buttons">
							<?php if($sm['config']['ios'] != ''){ ?>

							<a href="<?= $sm['config']['ios']; ?>" class="interstial-buttons-item" onclick="document.querySelector('.interstial-wrap').style.display = 'none';"
							    target="_blank">
								<img src="<?php echo $sm['config']['theme_url']; ?>/plugins/images/appstore-btn.png">
							</a>

							<?php } if($sm['config']['android'] != '') { ?>

							<a href="<?= $sm['config']['android']; ?>" class="interstial-buttons-item" onclick="document.querySelector('.interstial-wrap').style.display = 'none';"
							    target="_blank">
								<img src="<?php echo $sm['config']['theme_url']; ?>/plugins/images/playstore-btn.png">
							</a>

							<?php } ?>
						</div>
					</div>
				</div>
			</center>
		</div>

		<?php } ?>

		<!--off

		<? if($sm['user']['total_photos'] == 0 ) { ?>
			<div class="modal add-ava-modal" tabindex="-1" style="display:block;opacity: 1;">
				<div class="modal-dialog">
					<div class="modal-content binded" style="transform: scale(1); opacity: 1;">

						<div class="modal-body">           
			<div class="add-ava-visual-box">
				<div class="add-ava-visual-item" style="background-image: url(<?= $sm['config']['theme_url']; ?>/plugins/images/add-avatar-popup-photo-placeholder-01.png);"></div>
				<div class="add-ava-visual-item user-avatar" style="background-image: url(<?= $sm['user']['profile_photo']; ?>);">
					<div class="loading_indicator"></div>
				</div>
				<div class="add-ava-visual-item" style="background-image: url(<?= $sm['config']['theme_url']; ?>/plugins/images/add-avatar-popup-photo-placeholder-02.png);"></div>
			</div>

				<div class="add-ava-step-1 add-ava-step-upload">
					<div class="add-ava-upload-box">
						<a class="add-ava-up-btn fileUpload" id="firstPhoto" style="cursor: pointer;">
							Upload from your computer
						</a>
					</div>
					<div class="add-ava-desc">
						<p>Upload your photo, Users without avatar do not appear in Discover and can not interact completely in this site.</p>
					</div>
					<div class="photo-uploader">
						<div class="add-ava-note">
							Upload with one click     </div>
						<div class="add-ava-soc-buttons">
							<a class="in-button" id="insta-import2" data-type="in"></a>
						</div>
					</div>
				</div>

					<div class="add-ava-step-2 add-ava-step-upload">
						<div class="add-ava-desc">
							<h2 class="add-ava-desc-title">The best photo of <?= $sm['config']['name']; ?> history!</h2>
							<p>Let's check how much people is out there!</p>
						</div>
						<a class="add-ava-go-btn disabled" >Please give us 1 sec...</a>
					</div>
				</div>
						</div>
					</div>
				</div>

		<?php } ?>

		<div class="preload-photos"> </div>

		-->

		<audio id="notiSound" type="audio/wav" preload="false">
			<source src='<?= $sm[' config ']['site_url '];?>/sources/Notification.wav' />
		</audio>

		<audio id="callSound" type="audio/wav" preload="false">
			<source src='<?= $sm[' config ']['site_url '];?>/sources/Call.mp3' />
		</audio>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/jquery-2.1.1.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/jquery.form.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/bootstrap.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/classie.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/FlatNotifiy.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/fbphotobox.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/scroller.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/tinelo.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/sweetalert.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/peer.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/galleria-1.4.2.min.js"></script>

		<script src="<?php echo $sm['config']['theme_url']; ?>/assets/js/jquery.preload.js"></script>

		<script type="text/javascript" src="<?php echo $sm['config']['theme_url']; ?>/assets/js/emoji.min.js"></script>

		<script type="text/javascript" src="<?php echo $sm['config']['theme_url']; ?>/assets/js/twoo-emoji.js"></script>

		<script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

		<script src="https://checkout.stripe.com/checkout.js"></script>

		<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places&key=<?= siteConfig('google_maps'); ?>"></script>



		<?= getPlugins('js_file'); ?>
			<?= siteConfig('js'); ?>

</body>

</html>