	<script>
		url = "terms";
	</script>
	<div class="search-people-container"> 
		<div class="container relative search-people">
        	<div class="search-text">
				<?= $sm['lang'][102]['text']; ?>
			</div>
		</div>
	</div>			
   <div class="search-result-container">     
       <div class="container relative" style="backgrund:#fff; padding-top:35px;" >
		<?= siteConfig('privacy'); ?>
       </div> 
   </div>    
   
                 
    
                 
    